// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebConsumoApi.DBContext;

#nullable disable

namespace WebConsumoApi.Migrations.DbContextLogMigrations
{
    [DbContext(typeof(DbContextLog))]
    [Migration("20220818203831_log")]
    partial class log
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebConsumoApi.Models.Log", b =>
                {
                    b.Property<string>("sku")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("sku");

                    b.ToTable("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
