// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebConsumoApi.DBContext;

#nullable disable

namespace WebConsumoApi.Migrations.DbContextLogMigrations
{
    [DbContext(typeof(DbContextLog))]
    partial class DbContextLogModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebConsumoApi.Models.Log", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Sku");

                    b.ToTable("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
